---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggetho)
library(scopr)
library(sleepr)
```


```{r prepro, include=FALSE, echo=FALSE}

FEMALE_MALE_PALETTE <- c("#be2828ff", "#282896ff")
CONTROL_SD_PALETTE <- c( "#969696ff", "#3caa3cff")

METADATA <- "metadata.csv"
CACHE <- "./cache/"
#~ RESULT_DIR <- "./raw_results/"
RESULT_DIR <- "/data/ethoscope_results"

REMOTE_DIR <- "ftp://nas.lab.gilest.ro/auto_generated_data/ethoscope_results/"

met <- fread(METADATA)
met <- met[status == "OK" ]

met <- link_ethoscope_metadata(met, result_dir = RESULT_DIR)
                                      
                                                                            
dt <- load_ethoscope(met,
					   max_time=days(7),
					   reference_hour=9.0,
					   cache = CACHE,
					   FUN = sleep_annotation)




curate_data <- function(data){
  #data[, t := t - days(xmv(baseline_days))]
  #data <- data[is_interpolated == F]
	# first we remove animals that do not have enought data points
	valid_animals <- data[,.(t_range = max(t) - min(t)), by=id][t_range >= days(5)]$id
	data <- data[t > days(1) & 
				 t < days(6) &
				 id %in% valid_animals]
	data[, t := t - days(1)]
	
	data[,x_rel:=ifelse(xmv(region_id) > 10, 1-x, x)]
	data[,x_rel:=ifelse(xmv(inverted), 1-x_rel, x_rel)]
	norm_x <- function(x){
		min_x <- quantile(na.omit(x),probs=0.01)
		x <- x - min_x
		max_x <- quantile(na.omit(x),probs=0.99)
		x / max_x
		}
	data[, x_rel := norm_x(x_rel), by=id]
}

dt <- curate_data(dt)
```



```{r pressure}
dt[ ,treatment := ifelse(sdi == 0, "Control", "Treated"), meta=T]
pl <- 
ggetho(dt, aes(x = t,
               y = moving,
               colour = sex)) +
    stat_pop_etho(method = ggplot2::mean_cl_boot) +
    stat_ld_annotations() +
    scale_x_days() +
    facet_grid( treatment ~ .) 
```



```{r p}
set.seed(12)
sample <- sample(dt[,id, meta=T], 30, replace=F)

dt[ ,treatment := ifelse(sdi == 0, "Control", "Treated"), meta=T]
dt[ ,label  := interaction(1:.N, sex,treatment), meta=T]

pl2 <- 
ggetho(dt[id %in% sample], aes(x = t,
               y= label,
               z = moving)) +
    stat_tile_etho() +
    stat_ld_annotations() +
    scale_x_days() 
```




```{r s}
pdf("plot.pdf", w=4, h=4)
pl
pl2
dev.off()
```
